services:
    _defaults:
        autowire: true
        autoconfigure: true

    EonX\EasyDoctrine\Listeners\FixPostgreSqlDefaultSchemaListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }

    EonX\EasyDoctrine\ORM\Decorators\EntityManagerDecorator:
        arguments:
            $wrapped: '@.inner'
        decorates: doctrine.orm.default_entity_manager

    EonX\EasyDoctrine\Subscribers\EntityEventSubscriber:
        arguments:
            $entities:
                - 'App\Entity\Comment'
        tags:
            -
                name: doctrine.event_subscriber
                connection: default

    App\EventListener\CommentCreateListener:
        tags:
            - { name: kernel.event_listener, event: EonX\EasyDoctrine\Events\EntityCreatedEvent }

    App\EventListener\CommentUpdateListener:
        tags:
            - { name: kernel.event_listener, event: EonX\EasyDoctrine\Events\EntityUpdatedEvent }
